apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: "external"
---
apiServer:
  certSANs:
  - <MASTER IP ADRESS>
apiVersion: kubeadm.k8s.io/v1beta2
controlPlaneEndpoint: "<MASTER IP ADRESS>:6443"
kind: ClusterConfiguration
useHyperKubeImage: false
kubernetesVersion: "v1.19.0"
networking:
  dnsDomain: "cluster.local"
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.244.0.0/16"